### ISSUE TITLE
Is the policy relevant for two-argument variation of open?

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-critic-policy-inputoutput-prohibithighprecedentlogicaloperatorerrorhandling#3]
This needs to be investigated, documented, tested and perhaps even implemented

**Comment by Quipyowert2** [comment]
Yes, the policy is also relevant for two-arg open. Using two argument open, one can have the same bug as with three-argument open. I tested this policy on two argument open; it finds the bug.

The line:
```perl
open my $fh, "<not.there" || die;
```
doesn't die if the file `not.there` doesn't exist. whereas
```perl
open my $fh, "<not.there" or die;
```
prints
`Died at -e line 1.`

**Comment by jonasbn** [comment]
Thanks I will have a look at your PR (#6)
